apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: mp-qa
  name: mp-qa
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: mp-qa
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: paulesc93/flask_app:0.0.3
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
